export { ClientesResource } from './clientes.js';
export { VendedoresResource } from './vendedores.js';
export { ProdutosResource } from './produtos.js';
export { PrecosResource } from './precos.js';
export { EstoqueResource } from './estoque.js';
export { PedidosResource } from './pedidos.js';
export { FinanceirosResource } from './financeiros.js';
export { CadastrosResource } from './cadastros.js';
export { FiscalResource } from './fiscal.js';
export { GatewayResource } from './gateway.js';
export { MetadataResource } from './metadata.js';
export { DbExplorerResource } from './db-explorer.js';
export { DatasetResource, datasetRecord } from './dataset.js';
export { NotasResource } from './notas.js';
export { ConferenciaResource } from './conferencia.js';
